# Sets the Play environment in the server
# Run with: ansible-playbook -i hosts.ini playenv.yaml -u ubuntu --sudo
---
- hosts: ec2Instance
  vars:
  - ubuntu_release: quantal
  - user: ubuntu
  - group: ubuntu
  - play_version: 2.5.0

  tasks:
   - name: Install Unzip
     action: apt pkg=unzip state=latest install_recommends=yes

   - name: Install Git
     action: apt pkg=git state=latest install_recommends=yes

   - name: Install Authbind
     action: apt pkg=authbind state=latest install_recommends=yes

   - name: Configure Authbind
     action: copy content="" dest=/etc/authbind/byport/80 owner={{ user }} group={{ group }} mode=0500

   - name: Add Java repository to sources
     action: apt_repository repo='ppa:webupd8team/java'

   - name: Autoaccept license for Java
     action: shell echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections

   - name: Update APT package cache
     action: apt update_cache=yes

   - name: Install Java 8
     action: apt pkg=oracle-java8-installer state=latest install_recommends=yes

   - name: Set Java 8 Env
     action: apt pkg=oracle-java8-set-default state=latest install_recommends=yes
